language: node_js
node_js:
  - "0.10"
env:
  - DEV=true
before_install:
  - npm install -g grunt-cli
  - export PATH=$PATH:`pwd`/bin
before_script:
  - grunt
notifications:
  slack: ingenuitydesign:LRuHD7MwPHH5NFWrL3LVyKV3
after_success:
  - if [[ "$TRAVIS_BRANCH" != "master" ]]; then echo "Deployments are only done for the master branch. "; exit 0; fi

